phrases_pr = [
    "Mergeando PRs es como ordenar una pizza, siempre hay sorpresas.",
    "¿Revisar mi propio PR? Eso es como intentar autocriticarme en el espejo.",
    "Cuando me piden hacer un PR pequeño, es como pedirme que elija solo un dulce de la tienda.",
    "PR aprobado sin comentarios es más raro que encontrar papel higiénico al inicio de la pandemia.",
    "Cada vez que hago un PR, es un episodio nuevo de 'Esperanzas y Desilusiones'.",
    "Hacer PRs es mi forma de socializar. Sí, estoy disponible para fiestas.",
    "PRs sin conflictos son como los fantasmas, todos creen hasta que les toca ver uno.",
    "Mi PR es como una novela, largo y con muchos giros inesperados.",
    "La vida es corta, pero a veces los PRs no lo son.",
    "Hacer un PR sin revisión de código es como un día sin café, simplemente no funciona.",
    "Un PR bien hecho es como una buena broma, necesita el timing perfecto.",
    "Los PRs son como las citas a ciegas, nunca sabes con qué te vas a encontrar.",
    "Mergeando un PR sin testear es como saltar en bungee sin cuerda. Aventurero pero no recomendable.",
    "Enviar un PR es mi momento 'suelta el micrófono' del día.",
    "Resolver conflictos en PRs es como hacer malabares con cuchillos, un arte peligroso pero impresionante.",
    "Los PRs son como las cebollas, tienen capas y a veces te hacen llorar.",
    "Revisar PRs es como buscar el santo grial, una misión épica.",
    "Enviar un PR es declarar 'aquí estuve yo', con código en vez de graffiti.",
    "Los PRs son como el clima, siempre cambiando y a veces tormentosos.",
    "Hacer un PR es como lanzar un mensaje en una botella al océano digital.",
    "Un PR sin conflicto es como un día sin emails. Teóricamente posible, pero altamente improbable.",
    "Crear un PR es como hacer magia: conviertes café en código.",
    "Los PRs son como las películas de misterio, nunca sabes cómo van a terminar.",
    "Un buen PR es como un buen chiste, si tienes que explicarlo mucho, algo falló.",
    "Hacer un PR es mi versión de enviar una carta a Santa. Esperanzas altas, resultados inciertos.",
    "Los PRs son como los gatos, tienen su propia personalidad y no siempre cooperan.",
    "Enviar un PR es como lanzarse en paracaídas. Esperas que todo se abra correctamente.",
    "Revisar PRs es como ir a cazar tesoros. A veces encuentras oro, a veces solo calcetines viejos.",
    "PRs: porque compartir código debería ser tan emocionante como compartir chismes.",
    "Los PRs son como las citas: primero impresionas, luego negocias condiciones.",
    "Merge de PR: el momento en que tu código pasa de ser un héroe a ser parte del equipo.",
    "Los PRs son el reality show del desarrollo de software. Drama, acción y a veces, romance.",
    "Un PR exitoso es como un buen café: satisfactorio, necesario y motivo para celebrar.",
    "Hacer un PR es como proponer matrimonio: esperas un sí, pero preparado para cualquier cosa.",
    "PRs son como puzzles: divertidos hasta que faltan piezas o no encajan.",
    "Los PRs son como los sueños, grandes hasta que el revisor los trae de vuelta a la realidad.",
    "Enviar un PR es como enviar un hijo a la escuela: esperas lo mejor, pero te preparas para las llamadas.",
    "PRs: la mezcla perfecta entre esperanza, terror y el ocasional meme de gato.",
    "Resolver conflictos de PR es como mediar en una discusión de pareja: delicado y siempre buscando el compromiso.",
    "Los PRs son como las olas del mar: vienen, causan un poco de caos y luego se calman.",
    "Mi PR es como una serie de Netflix, esperas ansiosamente el próximo capítulo.",
    "Hacer un PR es mi deporte extremo preferido.",
    "Los PRs son como los exámenes sorpresa, nunca estás realmente preparado para ellos.",
    "Enviar un PR y esperar aprobación es como mandar un texto a tu crush y esperar que responda.",
    "Un PR rechazado es solo un 'inténtalo de nuevo' en el mundo del código.",
    "Revisar PRs es como ir de pesca, necesitas paciencia y a veces vuelves a casa con las manos vacías.",
    "Mi PR es como un reality show, lleno de drama y espera.",
    "Hacer un PR sin comentarios es como un día sin sol, sorprendentemente agradable.",
    "PRs son como los suegros, te juzgan pero tienes que lidiar con ellos.",
    "Enviar un PR es como enviar una carta a Santa, esperas lo mejor pero preparas para lo peor.",
    "Los conflictos en los PRs son como los puzzles, excepto que no siempre quieres terminarlos.",
    "Cuando finalmente mergearon mi PR, me sentí como si me hubieran coronado rey del mundo digital.",
    "Un PR sin conflictos es como un milagro de la naturaleza, raro y hermoso.",
    "Los PRs son como las olas del mar, vienen, rompen y a veces te arrastran.",
    "Escribir un PR es como escribir una carta de amor, pero al código.",
    "Mi PR es como una película de suspense, nunca sabes cómo va a terminar.",
    "Los PRs son como los autobuses, esperas eternamente y luego llegan tres de golpe.",
    "Revisar un PR es como desentrañar un misterio, con cada línea de código una pista.",
    "Un PR mergeado es un pequeño paso para el código, pero un gran salto para el desarrollador.",
    "Hacer un PR es como jugar al ajedrez, necesitas estrategia y a veces sacrificios.",
    "Los PRs son como los fuegos artificiales, brillan intensamente pero pueden explotar si no los manejas bien.",
    "Enviar un PR es admitir que necesitas ayuda para cruzar el río del código.",
    "Cada PR es una historia de amor entre el desarrollador y su código, con un final feliz no garantizado.",
    "Los PRs son como las pruebas de resistencia, te muestran de qué estás hecho.",
    "Resolver conflictos en un PR es como hacer las paces después de una pelea, necesario pero a veces incómodo.",
    "Un PR exitoso es como ganar en la lotería del código, las probabilidades siempre parecen en contra tuya.",
    "Los PRs son como los niños pequeños, necesitan atención, cuidado y a veces te hacen querer llorar.",
    "Hacer un PR es como tirarse de paracaídas, emocionante hasta que te das cuenta que tienes que aterrizar.",
    "Los PRs son el pan y la mantequilla del desarrollo de software, y a veces el cuchillo también.",
    "Un PR es como un acertijo envuelto en un misterio dentro de un enigma; y el reviewer, el único que tiene la clave."]

phrases_merged = [
    "¡PR aceptado! ¡Hora de celebrar con un bailecito de victoria!",
    "Un PR aceptado es como encontrar dinero en un bolsillo olvidado. ¡Pura felicidad!",
    "¡PR aceptado sin cambios! ¡Es como ganar la lotería del código!",
    "Cuando tu PR es aceptado de inmediato, sientes que tienes superpoderes de programación.",
    "¡Wohoo! ¡Mi PR fue aceptado! ¡Ahora puedo respirar tranquilo!",
    "Un PR aceptado es como el sol después de la tormenta: te llena de alegría y alivio.",
    "¡PR aceptado sin comentarios! ¿Magia? No, solo código bien escrito.",
    "Enviar un PR y que sea aceptado rápidamente es como sacarse un 10 en un examen sorpresa.",
    "¡PR aceptado! ¡Hora de festejar con un buen café y un poco de código más!",
    "Mi PR fue aceptado tan rápido que casi no tuve tiempo de preocuparme. ¡Qué alivio!",
    "Cuando tu PR es aceptado sin cambios, sientes que puedes conquistar el mundo del código.",
    "¡Bam! ¡PR aceptado! ¿Alguien más escuchó los fuegos artificiales?",
    "Un PR aceptado es como recibir un abrazo virtual del equipo de desarrollo.",
    "¡PR aceptado! ¡Hora de añadirlo a la lista de logros del día!",
    "Ver el mensaje 'PR aceptado' es como ver el final feliz de una película: satisfactorio y reconfortante.",
    "¡Mi PR fue aceptado más rápido que un rayo! ¡Qué emoción!",
    "Un PR aceptado es como una palmadita en la espalda del desarrollador: reconfortante y motivadora.",
    "¡PR aceptado! ¡Hora de relajarse y disfrutar del momento de gloria!",
    "Recibir la notificación de 'PR aceptado' es como recibir un regalo inesperado. ¡Alegría pura!",
    "¡PR aceptado sin conflictos! ¡Es como una obra maestra de la armonía del código!",
    "Un PR aceptado es como ganar el premio al mejor desarrollador del día. ¡Qué honor!",
    "¡PR aceptado! ¡Es hora de celebrar con un brindis virtual por el éxito del código!",
    "Ver el icono verde de 'PR aceptado' es como ver la luz al final del túnel del desarrollo.",
    "¡Mi PR fue aceptado con elogios! ¡Es como música para mis oídos de desarrollador!",
    "Un PR aceptado es como encontrar el tesoro al final del arcoíris. ¡Pura felicidad!",
    "¡PR aceptado! ¡Es hora de marcarlo en el calendario como día de victoria del código!",
    "Recibir la notificación de 'PR aceptado' es como recibir un abrazo virtual del equipo de revisión.",
    "¡PR aceptado! ¡Es como una medalla de oro en el mundo del desarrollo!",
    "Un PR aceptado es como un gol en el último minuto del partido: emocionante y gratificante.",
    "¡PR aceptado sin problemas! ¡Es como encontrar una aguja en un pajar, pero mejor!",
    "Ver el mensaje 'PR aceptado' es como recibir un rayo de sol en un día lluvioso. ¡Alegría instantánea!",
    "¡PR aceptado! ¡Es hora de celebrar con un bailecito de victoria y un poco de código más!",
    "Un PR aceptado es como llegar a la cima de una montaña después de una larga caminata: el esfuerzo vale la pena.",
    "¡PR aceptado! ¡Es como subir de nivel en el juego del desarrollo de software!",
    "Ver el icono verde de 'PR aceptado' es como ver un semáforo en verde: ¡sigue adelante sin parar!",
    "¡PR aceptado! ¡Es hora de poner en práctica el famoso ritual de la danza del PR aceptado!",
    "Un PR aceptado es como un regalo de cumpleaños adelantado: ¡sorpresa y alegría!",
    "¡PR aceptado! ¡Es como recibir un premio por excelencia en el mundo del código!",
    "Ver el mensaje 'PR aceptado' es como recibir un sí en una propuesta de matrimonio: ¡pura felicidad!",
    "¡PR aceptado! ¡Es como un golpe de suerte en el casino del desarrollo!",
    "Un PR aceptado es como encontrar una aguja en un pajar, pero con una lupa gigante. ¡Éxito!",
    "¡PR aceptado! ¡Es hora de celebrar con un brindis virtual y una ronda de aplausos para el equipo!",
    "Un PR aceptado es como una lluvia de confeti en el mundo del desarrollo. ¡Fiesta!",
    "¡PR aceptado! ¡Es hora de escribir la siguiente línea de código con una sonrisa en el rostro!",
    "Ver el icono verde de 'PR aceptado' es como recibir un billete de lotería ganador. ¡Alegría desbordante!",
    "¡PR aceptado! ¡Es como recibir un abrazo virtual de todo el equipo de desarrollo!",
    "Un PR aceptado es como encontrar la pieza faltante en un rompecabezas: ¡todo encaja perfectamente!",
    "¡PR aceptado! ¡Es como encontrar un oasis en medio del desierto del desarrollo de software!",
    "Un PR aceptado es como el primer sorbo de café por la mañana: ¡energía y satisfacción!",
    "¡PR aceptado! ¡Es hora de hacer una fiesta virtual para celebrar el éxito del código!",
    "Un PR aceptado es como el reconocimiento de tus habilidades de desarrollo. ¡Qué satisfacción!",
    "¡PR aceptado! ¡Es como abrir un regalo y encontrar exactamente lo que querías!",
    "Un PR aceptado es como una victoria en la guerra del código: ¡triunfo y gloria!",
    "¡PR aceptado! ¡Es hora de recibir los aplausos virtuales del equipo de desarrollo!",
    "Un PR aceptado es como encontrar una salida en un laberinto: ¡alivio y alegría!",
    "¡PR aceptado! ¡Es como alcanzar la meta en una carrera de relevos del desarrollo!",
    "Un PR aceptado es como una sonrisa del universo del código: ¡ilumina tu día!",
    "¡PR aceptado! ¡Es como recibir un ascenso en el escalafón del desarrollo de software!",
    "Un PR aceptado es como encontrar un billete de 100 dólares en un bolsillo olvidado: ¡pura alegría!",
    "¡PR aceptado! ¡Es hora de hacer una celebración virtual con todo el equipo de desarrollo!",
    "Un PR aceptado es como el final feliz de una película: ¡satisfactorio y reconfortante!",
    "¡PR aceptado! ¡Es como recibir un premio por excelencia en el mundo del código!",
    "Un PR aceptado es como un disparo al blanco en una competición de tiro: ¡precisión y éxito!",
    "¡PR aceptado! ¡Es hora de celebrar con un brindis virtual por el éxito del código!",
    "Un PR aceptado es como abrir una caja de sorpresas y encontrar solo cosas buenas. ¡Felicidad pura!",
    "¡PR aceptado! ¡Es como subir al podio en una competición de desarrollo de software!",
    "Un PR aceptado es como encontrar el Santo Grial en el desarrollo de software: ¡una búsqueda exitosa!",
    "¡PR aceptado! ¡Es como encontrar una perla en el fondo del océano del código!",
    "Un PR aceptado es como recibir un premio Nobel del desarrollo de software: ¡reconocimiento merecido!",
    "¡PR aceptado! ¡Es hora de escribir la siguiente línea de código con una sonrisa en el rostro!",
    "Un PR aceptado es como un golpe de suerte en el casino del desarrollo: ¡sorpresa y emoción!",
    "¡PR aceptado! ¡Es como recibir un abrazo virtual de todo el equipo de desarrollo!",
    "Un PR aceptado es como encontrar la pieza faltante en un rompecabezas: ¡todo encaja perfectamente!",
    "¡PR aceptado! ¡Es como encontrar un oasis en medio del desierto del desarrollo de software!",
    "Un PR aceptado es como el primer sorbo de café por la mañana: ¡energía y satisfacción!",
    "¡PR aceptado! ¡Es hora de hacer una fiesta virtual para celebrar el éxito del código!",
    "Un PR aceptado es como el reconocimiento de tus habilidades de desarrollo: ¡qué satisfacción!",
    "¡PR aceptado! ¡Es como abrir un regalo y encontrar exactamente lo que querías!",
    "Un PR aceptado es como una victoria en la guerra del código: ¡triunfo y gloria!",
    "¡PR aceptado! ¡Es hora de recibir los aplausos virtuales del equipo de desarrollo!",
    "Un PR aceptado es como encontrar una salida en un laberinto: ¡alivio y alegría!",
    "¡PR aceptado! ¡Es como alcanzar la meta en una carrera de relevos del desarrollo!",
    "Un PR aceptado es como una sonrisa del universo del código: ¡ilumina tu día!",
    "¡PR aceptado! ¡Es como recibir un ascenso en el escalafón del desarrollo de software!",
    "Un PR aceptado es como encontrar un billete de 100 dólares en un bolsillo olvidado: ¡pura alegría!",
    "¡PR aceptado! ¡Es hora de hacer una celebración virtual con todo el equipo de desarrollo!",
    "Un PR aceptado es como el final feliz de una película: ¡satisfactorio y reconfortante!",
    "¡PR aceptado! ¡Es como recibir un premio por excelencia en el mundo del código!",
    "Un PR aceptado es como un disparo al blanco en una competición de tiro: ¡precisión y éxito!",
    "¡PR aceptado! ¡Es hora de celebrar con un brindis virtual por el éxito del código!",
    "Un PR aceptado es como abrir una caja de sorpresas y encontrar solo cosas buenas. ¡Felicidad pura!",
    "¡PR aceptado! ¡Es como subir al podio en una competición de desarrollo de software!",
    "Un PR aceptado es como encontrar el Santo Grial en el desarrollo de software: ¡una búsqueda exitosa!",
    "¡PR aceptado! ¡Es como encontrar una perla en el fondo del océano del código!",
    "Un PR aceptado es como recibir un premio Nobel del desarrollo de software: ¡reconocimiento merecido!"
]

phrases_closed = [
    "¡PR rechazado! ¡Hora de revisar el código y volver a intentarlo!",
    "Un PR rechazado es como un gol en propia puerta: ¡un error que duele!",
    "¡PR rechazado! ¡Es como un choque de realidad en el mundo del desarrollo!",
    "Recibir la notificación de 'PR rechazado' es como un balde de agua fría en el desarrollo.",
    "¡PR rechazado sin piedad! ¡Es como una bofetada de realidad en el rostro!",
    "Un PR rechazado es como una negativa en una propuesta de matrimonio: duele un poco.",
    "¡PR rechazado! ¡Hora de recoger los pedazos y mejorar el código!",
    "Ver el mensaje 'PR rechazado' es como ver un semáforo en rojo: ¡detente y revisa tu camino!",
    "¡PR rechazado! ¡Es como volver a la casilla de salida en el juego del desarrollo!",
    "Recibir la notificación de 'PR rechazado' es como un suspenso en un examen importante.",
    "¡PR rechazado sin contemplaciones! ¡Es como una bofetada de realidad en el código!",
    "Un PR rechazado es como un resfriado en pleno verano: inesperado y molesto.",
    "¡PR rechazado! ¡Hora de analizar los errores y aprender de ellos!",
    "Ver el icono rojo de 'PR rechazado' es como ver una señal de peligro en el camino del desarrollo.",
    "¡PR rechazado! ¡Es como una ducha fría en medio del invierno del código!",
    "Un PR rechazado es como una parada inesperada en un viaje por carretera: frustrante pero necesario.",
    "¡PR rechazado! ¡Hora de tomar un respiro, aprender de los errores y volver con más fuerza!",
    "Recibir la notificación de 'PR rechazado' es como una advertencia de error en el código de la vida.",
    "¡PR rechazado sin contemplaciones! ¡Es como una llamada de atención del código!",
    "Un PR rechazado es como un tropiezo en una carrera: duele un poco pero te hace más fuerte.",
    "¡PR rechazado! ¡Es como un gol en contra en el último minuto del partido: doloroso!",
    "Ver el mensaje 'PR rechazado' es como ver una luz roja parpadeante en el tablero de control.",
    "¡PR rechazado! ¡Es como una página arrancada del libro del desarrollo!",
    "Un PR rechazado es como un no en una solicitud de amistad: desilusionante pero no el fin del mundo.",
    "¡PR rechazado! ¡Hora de volver a la mesa de trabajo y pulir el código!",
    "Recibir la notificación de 'PR rechazado' es como un recordatorio de que nadie es perfecto en el desarrollo.",
    "¡PR rechazado sin compasión! ¡Es como una patada en el ego del desarrollador!",
    "Un PR rechazado es como una gota de lluvia en un día soleado: inesperado y molesto.",
    "¡PR rechazado! ¡Es como un error 404 en el camino del desarrollo!",
    "Ver el icono rojo de 'PR rechazado' es como ver un semáforo en rojo en medio de un viaje.",
    "¡PR rechazado! ¡Hora de revisar el código y corregir los errores!",
    "Un PR rechazado es como una respuesta negativa en una entrevista de trabajo: desalentador pero no el fin del mundo.",
    "¡PR rechazado! ¡Es como un retroceso en el avance del código!",
    "Recibir la notificación de 'PR rechazado' es como una llamada de atención del código: ¡presta atención!",
    "¡PR rechazado sin miramientos! ¡Es como una bofetada de realidad en el desarrollo!",
    "Un PR rechazado es como un giro inesperado en una película: te deja sin palabras.",
    "¡PR rechazado! ¡Hora de reflexionar, aprender y mejorar el código!",
    "Ver el mensaje 'PR rechazado' es como recibir una crítica dura pero constructiva.",
    "¡PR rechazado! ¡Es como una señal de alto en el camino del desarrollo!",
    "Un PR rechazado es como una línea de código rota: necesita ser reparada para avanzar.",
    "¡PR rechazado! ¡Hora de levantarse, sacudirse el polvo y volver a intentarlo!",
    "Recibir la notificación de 'PR rechazado' es como un golpe en el estómago del desarrollador.",
    "¡PR rechazado sin piedad! ¡Es como una llamada de atención del código!",
    "Un PR rechazado es como un error 500 en el servidor del desarrollo: ¡algo salió mal!",
    "¡PR rechazado! ¡Es como un bloqueo en el flujo del desarrollo!",
    "Ver el icono rojo de 'PR rechazado' es como ver una señal de peligro en el camino del código.",
    "¡PR rechazado! ¡Hora de revisar el código y encontrar una solución!",
    "Un PR rechazado es como una línea de código tachada: necesita ser reescrita para ser útil.",
    "¡PR rechazado! ¡Es como una negativa en una solicitud de crédito: desilusionante pero no el fin del mundo!",
    "Recibir la notificación de 'PR rechazado' es como una llamada de atención del código: ¡presta atención!",
    "¡PR rechazado sin miramientos! ¡Es como una bofetada de realidad en el desarrollo!",
    "Un PR rechazado es como un giro inesperado en una montaña rusa: te deja mareado pero listo para el siguiente viaje.",
    "¡PR rechazado! ¡Hora de reflexionar, aprender y mejorar el código!",
    "Ver el mensaje 'PR rechazado' es como recibir una crítica dura pero constructiva: ¡nunca es fácil!",
    "¡PR rechazado! ¡Es como una señal de alto en el camino del desarrollo: detente y reflexiona!",
    "Un PR rechazado es como una línea de código rota: necesita ser reparada para avanzar.",
    "¡PR rechazado! ¡Hora de levantarse, sacudirse el polvo y volver a intentarlo!",
    "Recibir la notificación de 'PR rechazado' es como un golpe en el estómago del desarrollador: ¡duele pero te hace más fuerte!",
    "¡PR rechazado sin piedad! ¡Es como una llamada de atención del código: ¡presta atención!",
    "Un PR rechazado es como un error 500 en el servidor del desarrollo: ¡algo salió mal y necesita ser arreglado!",
    "¡PR rechazado! ¡Es como un bloqueo en el flujo del desarrollo: necesita ser superado para avanzar!",
    "Ver el icono rojo de 'PR rechazado' es como ver una señal de peligro en el camino del código: ¡detente y revisa!",
    "¡PR rechazado! ¡Hora de revisar el código y encontrar una solución: ¡siempre hay una forma de mejorar!",
    "Un PR rechazado es como una línea de código tachada: necesita ser reescrita para ser útil y funcional.",
    "¡PR rechazado! ¡Es como una negativa en una solicitud de crédito: desilusionante pero no el fin del mundo!",
    "Recibir la notificación de 'PR rechazado' es como una llamada de atención del código: ¡presta atención y aprende de tus errores!",
    "¡PR rechazado sin miramientos! ¡Es como una bofetada de realidad en el desarrollo: duele pero te hace más fuerte!",
    "Un PR rechazado es como un giro inesperado en una montaña rusa: te deja mareado pero listo para el siguiente viaje emocionante.",
    "¡PR rechazado! ¡Hora de reflexionar, aprender y mejorar el código: siempre hay margen para crecer y mejorar!",
    "Ver el mensaje 'PR rechazado' es como recibir una crítica dura pero constructiva: ¡nunca es fácil pero siempre es necesario crecer!",
    "¡PR rechazado! ¡Es como una señal de alto en el camino del desarrollo: detente, reflexiona y encuentra una solución!",
    "Un PR rechazado es como una línea de código rota: necesita ser reparada y corregida para avanzar con éxito.",
    "¡PR rechazado! ¡Hora de levantarse, sacudirse el polvo y volver a intentarlo con determinación!",
    "Recibir la notificación de 'PR rechazado' es como un golpe en el estómago del desarrollador: ¡duele pero te recuerda que aún hay mucho por aprender!",
    "¡PR rechazado sin piedad! ¡Es como una llamada de atención del código: ¡presta atención y trabaja en mejorar!",
    "Un PR rechazado es como un error 500 en el servidor del desarrollo: ¡algo salió mal y necesitas arreglarlo para avanzar!",
    "¡PR rechazado! ¡Es como un bloqueo en el flujo del desarrollo: necesita ser superado con determinación y esfuerzo!",
    "Ver el icono rojo de 'PR rechazado' es como ver una señal de peligro en el camino del código: ¡detente, reflexiona y encuentra una solución!",
    "¡PR rechazado! ¡Hora de revisar el código y encontrar una solución: siempre hay una forma de mejorar y crecer como desarrollador!",
    "Un PR rechazado es como una línea de código tachada: necesita ser reescrita y mejorada para ser útil y funcional en el proyecto.",
    "¡PR rechazado! ¡Es como una negativa en una solicitud de crédito: desilusionante pero una oportunidad para aprender y mejorar!",
    "Recibir la notificación de 'PR rechazado' es como una llamada de atención del código: ¡presta atención, aprende y crece como desarrollador!",
    "¡PR rechazado sin miramientos! ¡Es como una bofetada de realidad en el desarrollo: duele pero te recuerda que siempre hay margen para mejorar!",
    "Un PR rechazado es como un giro inesperado en una montaña rusa: te deja mareado pero con ganas de volver a intentarlo con más determinación y enfoque.",
    "¡PR rechazado! ¡Hora de reflexionar, aprender y mejorar el código: cada error es una oportunidad para crecer y mejorar como desarrollador!",
    "Ver el mensaje 'PR rechazado' es como recibir una crítica dura pero constructiva: ¡nunca es fácil pero siempre es necesario para mejorar y avanzar!",
    "¡PR rechazado! ¡Es como una señal de alto en el camino del desarrollo: detente, reflexiona y encuentra una solución para seguir adelante con éxito!",
    "Un PR rechazado es como una línea de código rota: necesita ser reparada y corregida para avanzar con éxito en el proyecto y cumplir con los estándares de calidad.",
    "¡PR rechazado! ¡Hora de levantarse, sacudirse el polvo y volver a intentarlo con determinación y compromiso!",
    "Recibir la notificación de 'PR rechazado' es como un golpe en el estómago del desarrollador: ¡duele pero también te hace más fuerte y te recuerda que siempre hay oportunidades para mejorar y crecer!",
    "¡PR rechazado sin piedad! ¡Es como una llamada de atención del código: ¡presta atención, aprende de tus errores y trabaja en mejorar tus habilidades como desarrollador!",
    "Un PR rechazado es como un error 500 en el servidor del desarrollo: ¡algo salió mal y necesitas corregirlo con urgencia para garantizar el éxito del proyecto y la satisfacción del cliente!",
    "¡PR rechazado! ¡Es como un bloqueo en el flujo del desarrollo: necesitas superarlo con determinación, creatividad y trabajo en equipo para encontrar una solución que cumpla con los requisitos del proyecto y las expectativas del cliente!",
    "Ver el icono rojo de 'PR rechazado' es como ver una señal de peligro en el camino del código: ¡detente, reflexiona y busca ayuda si es necesario para resolver los problemas y avanzar con éxito en el proyecto!",
    "¡PR rechazado! ¡Hora de revisar el código y encontrar una solución: siempre hay una forma de mejorar y superar los obstáculos para alcanzar tus metas y objetivos como desarrollador!",
    "Un PR rechazado es como una línea de código tachada: necesita ser reescrita y mejorada para cumplir con los estándares de calidad del proyecto y contribuir al éxito del equipo de desarrollo!",
    "¡PR rechazado! ¡Es como una negativa en una solicitud de crédito: desilusionante pero una oportunidad para aprender de tus errores, fortalecer tus habilidades y seguir adelante con determinación y confianza en ti mismo!",
    "Recibir la notificación de 'PR rechazado' es como una llamada de atención del código: ¡presta atención, aprende de tus errores y trabaja en mejorar tus habilidades y conocimientos para convertirte en un desarrollador aún mejor!",
    "¡PR rechazado sin miramientos! ¡Es como una bofetada de realidad en el desarrollo: duele pero también te motiva a esforzarte más, aprender de tus errores y buscar constantemente formas de mejorar y crecer como profesional y como persona!",
    "Un PR rechazado es como un giro inesperado en una montaña rusa: te deja mareado pero también te recuerda que la vida está llena de altibajos y que cada desafío es una oportunidad para fortalecerte, aprender y seguir adelante con determinación y valentía!",
    "¡PR rechazado! ¡Hora de reflexionar, aprender y mejorar el código: cada desafío es una oportunidad para crecer, evolucionar y convertirte en la mejor versión de ti mismo como desarrollador y como ser humano!"
]
